import { z } from 'zod';

/**
 * Skill metadata from SKILL.md frontmatter
 * Used for skill discovery and matching
 */
export interface SkillMetadata {
  /** Unique name of the skill */
  name: string;
  /** Human-readable description */
  description: string;
  /** License identifier (e.g., MIT, Apache-2.0) */
  license?: string;
  /** Compatibility information */
  compatibility?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
  /** List of allowed tools for this skill */
  allowedTools?: string[];
}

/**
 * Complete Skill definition including body and file paths
 */
export interface Skill extends SkillMetadata {
  /** Body content from SKILL.md (everything after frontmatter) */
  body: string;
  /** Path to scripts directory */
  scriptsDir?: string;
  /** Path to references directory */
  referencesDir?: string;
  /** Path to assets directory */
  assetsDir?: string;
}

/**
 * Task status values
 */
export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * Error types for task failures
 */
export type ErrorType = 'RETRYABLE' | 'FATAL' | 'USER_ERROR' | 'SKILL_ERROR';

/**
 * Task error information
 */
export interface TaskError {
  /** Error classification */
  type: ErrorType;
  /** Human-readable error message */
  message: string;
  /** Error code (optional) */
  code?: string;
  /** Stack trace (optional, for debugging) */
  stack?: string;
}

/**
 * Task definition
 */
export interface Task {
  /** Unique task ID */
  id: string;
  /** Natural language requirement for this task */
  requirement: string;
  /** Current task status */
  status: TaskStatus;
  /** ID of the subagent executing this task */
  subagentId?: string;
  /** Name of the skill to execute */
  skillName?: string;
  /** Parameters for the skill */
  params?: Record<string, unknown>;
  /** Task execution result */
  result?: unknown;
  /** Error information if task failed */
  error?: TaskError;
  /** IDs of tasks this task depends on */
  dependencies: string[];
  /** IDs of tasks that depend on this task */
  dependents: string[];
  /** Task creation timestamp */
  createdAt: Date;
  /** Task start timestamp */
  startedAt?: Date;
  /** Task completion timestamp */
  completedAt?: Date;
  /** Number of retry attempts */
  retryCount: number;
}

/**
 * LLM message for chat completions
 */
export interface Message {
  /** Message role */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** Message content */
  content: string;
  /** Tool call ID (for tool responses) */
  tool_call_id?: string;
}

/**
 * Tool definition for function calling
 */
export interface ToolDefinition {
  /** Tool name */
  name: string;
  /** Tool description */
  description: string;
  /** Tool parameters schema */
  parameters: Record<string, unknown>;
}

/**
 * Tool call result
 */
export interface ToolCall {
  /** Tool call ID */
  id: string;
  /** Tool name */
  name: string;
  /** Tool arguments */
  arguments: Record<string, unknown>;
}

/**
 * Task execution result
 */
export interface TaskResult {
  /** Whether the task succeeded */
  success: boolean;
  /** Task result data */
  data?: unknown;
  /** Error information if task failed */
  error?: TaskError;
}

/**
 * Requirement analysis result
 */
export interface RequirementAnalysis {
  /** Summary of the requirement */
  summary: string;
  /** Key entities mentioned */
  entities?: string[];
  /** Intent classification */
  intent?: string;
  /** Suggested skills */
  suggestedSkills?: string[];
}

/**
 * Task plan generated by MainAgent
 */
export interface TaskPlan {
  /** Plan ID */
  id: string;
  /** Original requirement */
  requirement: string;
  /** Whether the requirement needs clarification */
  needsClarification?: boolean;
  /** Prompt for clarifying the requirement */
  clarificationPrompt?: string | null;
  /** List of tasks in the plan */
  tasks: Array<{
    id: string;
    requirement: string;
    skillName: string;
    params?: Record<string, unknown>;
    dependencies: string[];
  }>;
}

/**
 * System configuration constants
 */
export const CONFIG = {
  /** Maximum concurrent subagents */
  MAX_CONCURRENT_SUBAGENTS: 5,
  /** Maximum task queue size */
  MAX_QUEUE_SIZE: 100,
  /** Maximum replan attempts for failed tasks */
  MAX_REPLAN_ATTEMPTS: 3,
  /** Individual task timeout - must cover LLM retries (90s × 3 + backoff ≈ 300s) */
  TASK_TIMEOUT_MS: parseInt(process.env.TASK_TIMEOUT_MS || '400000', 10),
  /** Total workflow timeout - for multiple sequential tasks */
  TOTAL_TIMEOUT_MS: parseInt(process.env.TOTAL_TIMEOUT_MS || '600000', 10),
  /** LLM API timeout - NVIDIA API can be slow for complex prompts */
  LLM_TIMEOUT_MS: parseInt(process.env.LLM_TIMEOUT_MS || '90000', 10),
  /** Script execution timeout - should be less than TASK_TIMEOUT_MS */
  SCRIPT_TIMEOUT_MS: parseInt(process.env.SCRIPT_TIMEOUT_MS || '180000', 10),
  /** Skill directory path */
  SKILL_DIRECTORY: './skills/',
  /** GLM model name */
  LLM_MODEL: 'z-ai/glm4.7',
  /** LLM API base URL */
  LLM_BASE_URL: 'https://integrate.api.nvidia.com/v1',
  /** LLM temperature */
  LLM_TEMPERATURE: 0.7,
  /** Task cleanup interval (5 minutes) */
  TASK_CLEANUP_INTERVAL_MS: 300000,
  /** Task retention time (1 hour) */
  TASK_RETENTION_TIME_MS: 3600000,
} as const;

// ============================================================================
// Zod Schemas for Runtime Validation
// ============================================================================

/**
 * Zod schema for SkillMetadata
 */
export const SkillMetadataSchema = z.object({
  name: z.string(),
  description: z.string(),
  license: z.string().optional(),
  compatibility: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
  allowedTools: z.array(z.string()).optional(),
});

/**
 * Zod schema for Skill
 */
export const SkillSchema = SkillMetadataSchema.extend({
  body: z.string(),
  scriptsDir: z.string().optional(),
  referencesDir: z.string().optional(),
  assetsDir: z.string().optional(),
});

/**
 * Zod schema for ErrorType
 */
export const ErrorTypeSchema = z.enum(['RETRYABLE', 'FATAL', 'USER_ERROR', 'SKILL_ERROR']);

/**
 * Zod schema for TaskError
 */
export const TaskErrorSchema = z.object({
  type: ErrorTypeSchema,
  message: z.string(),
  code: z.string().optional(),
  stack: z.string().optional(),
});

/**
 * Zod schema for TaskStatus
 */
export const TaskStatusSchema = z.enum(['pending', 'running', 'completed', 'failed']);

/**
 * Zod schema for Task
 */
export const TaskSchema = z.object({
  id: z.string(),
  requirement: z.string(),
  status: TaskStatusSchema,
  subagentId: z.string().optional(),
  skillName: z.string().optional(),
  params: z.record(z.unknown()).optional(),
  result: z.unknown().optional(),
  error: TaskErrorSchema.optional(),
  dependencies: z.array(z.string()),
  dependents: z.array(z.string()),
  createdAt: z.date(),
  startedAt: z.date().optional(),
  completedAt: z.date().optional(),
  retryCount: z.number(),
});

/**
 * Zod schema for Message
 */
export const MessageSchema = z.object({
  role: z.enum(['system', 'user', 'assistant', 'tool']),
  content: z.string(),
  tool_call_id: z.string().optional(),
});

/**
 * Zod schema for ToolDefinition
 */
export const ToolDefinitionSchema = z.object({
  name: z.string(),
  description: z.string(),
  parameters: z.record(z.unknown()),
});

/**
 * Zod schema for ToolCall
 */
export const ToolCallSchema = z.object({
  id: z.string(),
  name: z.string(),
  arguments: z.record(z.unknown()),
});

/**
 * Zod schema for TaskResult
 */
export const TaskResultSchema = z.object({
  success: z.boolean(),
  data: z.unknown().optional(),
  error: TaskErrorSchema.optional(),
});

/**
 * Zod schema for RequirementAnalysis
 */
export const RequirementAnalysisSchema = z.object({
  summary: z.string(),
  entities: z.array(z.string()).optional(),
  intent: z.string().optional(),
  suggestedSkills: z.array(z.string()).optional(),
});

/**
 * Zod schema for TaskPlan
 */
export const TaskPlanSchema = z.object({
  id: z.string(),
  requirement: z.string(),
  needsClarification: z.boolean().optional(),
  clarificationPrompt: z.string().optional().nullable(),
  tasks: z.array(z.object({
    id: z.string(),
    requirement: z.string(),
    skillName: z.string(),
    params: z.record(z.unknown()).optional(),
    dependencies: z.array(z.string()),
  })),
});

// ============================================================================
// Type inference from schemas (for runtime validation)
// ============================================================================

/** Inferred SkillMetadata type from schema */
export type SkillMetadataInferred = z.infer<typeof SkillMetadataSchema>;
/** Inferred Skill type from schema */
export type SkillInferred = z.infer<typeof SkillSchema>;
/** Inferred TaskError type from schema */
export type TaskErrorInferred = z.infer<typeof TaskErrorSchema>;
/** Inferred Task type from schema */
export type TaskInferred = z.infer<typeof TaskSchema>;
/** Inferred TaskResult type from schema */
export type TaskResultInferred = z.infer<typeof TaskResultSchema>;
/** Inferred RequirementAnalysis type from schema */
export type RequirementAnalysisInferred = z.infer<typeof RequirementAnalysisSchema>;
/** Inferred TaskPlan type from schema */
export type TaskPlanInferred = z.infer<typeof TaskPlanSchema>;
